/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Context menu item
 */
export type ContextNavMenuitem = {
  [k: string]: unknown;
};
export type Blade =
  | Agenda
  | Author
  | Cards
  | Comparisontable
  | Contactus
  | Contiguouscontainer
  | Faq
  | Footnote
  | Form
  | Helloworld
  | Horizontaltabs
  | Index
  | Logogrid
  | Marquee
  | Media1
  | Notification
  | Nup
  | Nupfixed
  | Offer
  | Oneup
  | Open
  | Productfeature
  | Productportfolio
  | Promotion
  | Simpletable
  | Story
  | Summary
  | Tableofcontents
  | Text
  | Textlongform
  | Textmainbody
  | Textwithimage
  | Trailheadmfe
  | Videoblade;
export type Background = Custom | Standard | Swoosh | Container;
export type CurrencyNumberStyle =
  | "USD_english"
  | "USD_english_french"
  | "USD_spanish"
  | "USD_chinese_simplified"
  | "USD_chinese_traditional"
  | "USD_korean"
  | "USD_thai"
  | "GBP_english"
  | "INR_english"
  | "YEN_japanese"
  | "EUR_german"
  | "EUR_french"
  | "EUR_dutch"
  | "EUR_italian"
  | "EUR_spanish"
  | "EUR_finish"
  | "R$_portuguese"
  | "CNF_french_german"
  | "kr_danish"
  | "kr_swedish";
export type Video = Vidyard | Kaltura | Html5 | Youtube;
export type IndexBladeFilters = FilterGroup[];
export type ToggleControl = boolean;
export type TableSection = {
  cells?: TableCell[];
}[];
export type Blades = Blade[];

export interface Page {
  nav?: Nav;
  context_nav?: ContextNav;
  blades?: Blades;
  pageAttrs?: {
    read_time?: string;
    livechat?: {
      enabled?: boolean;
      headline?: string;
      name_capture_campaign_id?: string;
      use_default_prompt?: boolean;
      prompts?: string[];
      [k: string]: unknown;
    };
    agentforce?: {
      org_id?: string;
      deployment_dev_name?: string;
      messaging_url?: string;
      script_url?: string;
      [k: string]: unknown;
    };
    content_type?: string;
    seo_page_type?: string;
    seo_product_name?: string;
    alt_seo_product_name?: string;
    autogenerate_json_ld?: boolean;
    page_theme_variant?: string;
    page_background_type?: PageBackground;
    [k: string]: unknown;
  };
  taxonomy?: {
    pageTagsAuto?: Tag[];
    pageTagsManual?: Tag[];
    [k: string]: unknown;
  };
  templateId?: string;
  templateName?: string;
  theme?: string;
  globalNavEnabled?: boolean;
  footerEnabled?: boolean;
  footer?: Footer;
  [k: string]: unknown;
}
export interface Nav {
  showRegion?: boolean;
  showAccount?: boolean;
  showSearch?: boolean;
  showContact?: boolean;
  showCustomerOffer?: boolean;
  showProspectOffer?: boolean;
  customerOfferOverride?: Link;
  prospectOfferOverride?: Link;
  headerType?: string;
  [k: string]: unknown;
}
export interface Link {
  /**
   * The label of the button.
   */
  label?: string;
  typeOptions?: {
    [k: string]: unknown;
  };
  ariaLabel?: string;
  url?: string;
  target?: "_self" | "_parent" | "_top" | "_blank";
  isSpa?: boolean;
  [k: string]: unknown;
}
/**
 * Context navigation is part of the overall navigation system and works in conjuction with top navigation
 */
export interface ContextNav {
  newWindowAlt?: string;
  variation: "static" | "dynamic" | "minimized" | "standalone";
  /**
   * Extra spacing to vertically move the navigation items up (by specifying a negative value i.e. '-10px') or down (by specifying a positive value i.e. '10px').
   */
  navTopExtraSpacing?: string;
  /**
   * For the standalone variation only: Desired width of the logo used in the navigation i.e. '156px'.
   */
  standaloneLogoWidth?: string;
  /**
   * For the standalone variation only: If true, centers the navigation items, otherwise navigation items are left-aligned by default.
   */
  standaloneCentered?: boolean;
  isLogoEnabled: boolean;
  propertyLogo?: Image;
  propertyTitle: Link;
  menuGroup: ContextNavMenugroup;
  utilityNavigation?: ContextNavUtilityNav;
  orgSelector?: ContextNavOrgSelector;
  [k: string]: unknown;
}
export interface Image {
  kind?: "image";
  title?: string | null;
  src: string;
  width: number | string;
  height: number | string;
  alt?: string;
  hint?: string;
  is_decorative?: boolean;
  typeOptions?: {
    [k: string]: unknown;
  };
  sizes?: Size[];
  image_background_circle_color?: string;
  image_background_gradient_color?: string;
  image_alignment?: string;
  file_url?: string;
}
export interface Size {
  src?: string;
  width?: number;
  height?: number;
  [k: string]: unknown;
}
/**
 * Group of menu items
 */
export interface ContextNavMenugroup {
  ID?: number;
  eyebrowHeading?: string;
  /**
   * @minItems 1
   */
  menuItems: ContextNavMenuitem[];
  ctaLink?: Link;
  hasSeparator?: boolean;
  [k: string]: unknown;
}
/**
 * Context menu utility navigation items
 */
export interface ContextNavUtilityNav {
  ctamain?: {
    cta?: Cta;
    inMobileHeader?: boolean;
    isSpa?: boolean;
    [k: string]: unknown;
  };
  ctasecondary?: {
    cta?: Cta;
    inMobileHeader?: boolean;
    isSpa?: boolean;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface Cta {
  /**
   * The label of the button.
   */
  label?: string;
  ariaLabel?: string;
  url?: string;
  /**
   * Icon identifier
   */
  icon?: string;
  variant?: "primary" | "secondary" | "tertiary" | "text" | "trial";
  target?: "_self" | "_parent" | "_top" | "_blank";
  id?: string | number;
  source?: "standard-link" | "modal-link" | "custom-action-link";
  custom_action_options?: {
    event_code?: string;
    workflow_uri?: string;
    name_capture_campaign_id?: string;
    action_template?: "everybody-demo-org" | "event-sign-up" | "offer";
    [k: string]: unknown;
  };
  linkAttributes?: {
    key?: string;
    value?: string;
    [k: string]: unknown;
  }[];
  modal_variant?: string;
  [k: string]: unknown;
}
/**
 * Context nav organization selector
 */
export interface ContextNavOrgSelector {
  selectorLabel?: string;
  title?: string;
  /**
   * @minItems 1
   */
  orgList?: ContextNavOrg[];
  footer?: Link;
  [k: string]: unknown;
}
/**
 * Context nav organization list
 */
export interface ContextNavOrg {
  ID?: number;
  link?: Link;
  email?: string;
  action?: string;
  icon?: {
    src?: string;
    alt?: string;
    [k: string]: unknown;
  };
  helpbubble?: string;
  description?: string;
  logo?: {
    src?: string;
    alt?: string;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface Agenda {
  attributes?: {
    audience_segment?: string[];
    theme_variant?: string;
    minimize_blade_spacing_bottom?: boolean;
    minimize_blade_spacing?: boolean;
    experiment_id?: string;
    experiment_type?: string;
    eyebrow?: Eyebrow;
    headline: string;
    headline_font_color?: string;
    subheadline?: string;
    description?: string;
    anchor_id?: string;
    link_1?: Cta;
    link_2?: Cta;
    blade_background_type?: Background;
    esi_blade_flag?: string;
    esi_blade_variant?: string;
    esi_blade_rule?: string;
  };
  name: "sf/agenda";
  id: string;
  tab_items?: CardAgendaCategory[];
  [k: string]: unknown;
}
export interface Eyebrow {
  label?: string;
  image?: Image;
  icon?: Icon;
  info_bubble?: string;
  hint?: string;
  character_count?: string;
  [k: string]: unknown;
}
export interface Icon {
  kind?: "icon";
  label?: string;
  src: string;
  decorative?: boolean;
  ariaLabel?: string;
  hint?: string;
}
export interface Custom {
  kind: "custom_background";
  blade_background_color?: string;
  blade_custom_image_desktop: Image;
  blade_custom_image_mobile: Image;
  blade_background_gradient_direction?: string;
}
export interface Standard {
  kind: "standard_background";
  blade_background_color?: string;
  blade_background_image?: Image;
  blade_background_shape?: string;
  blade_background_gradient_direction?: string;
}
export interface Swoosh {
  kind: "swoosh_background";
  blade_background_color: string;
}
export interface Container {
  kind: "container_background";
  blade_background_color?: string;
  blade_background_image?: Image;
  blade_background_image_position?: string;
  blade_background_shape?: string;
  blade_background_gradient_direction?: string;
}
export interface CardAgendaCategory {
  id: string;
  kind: "card_agenda-category";
  label: string;
  content?: CardAgendaSubCategory[];
}
export interface CardAgendaSubCategory {
  id: string;
  kind: "card_agenda-subcategory";
  label?: string;
  media_items?: CardAgendaItem[];
}
export interface CardAgendaItem {
  id: string;
  kind: "card_agenda-item";
  title: string;
  start_time: string;
  end_time?: string;
  location?: string;
  description?: string;
  image?: Icon | Image;
  link_1?: Link;
}
export interface Author {
  attributes?: {
    audience_segment?: string[];
    theme_variant?: string;
    minimize_blade_spacing?: boolean;
    minimize_blade_spacing_bottom?: boolean;
    experiment_id?: string;
    experiment_type?: string;
    author_image?: Image;
    full_name: string;
    headline?: string;
    description: string;
    corner_image?: Image;
    link_1?: Cta;
    blade_background_type?: Background;
    esi_blade_flag?: string;
    esi_blade_variant?: string;
    esi_blade_rule?: string;
  };
  name: "sf/author";
  id: string;
  [k: string]: unknown;
}
export interface Cards {
  attributes?: {
    card_layout?: string;
    headline?: string;
  };
  name: "sf/cards";
  id: string;
  media_items?: (
    | CardResource
    | CardHeadshot
    | CardStory
    | CardQuote
    | CardStatistic
    | CardEvent
    | CardContactUs
    | CardCategory
    | CardPricingEdition
    | CardLogomark
    | CardShowHide
    | CardProduct
    | CardProductAddon
    | CardProductAddonAnchor
    | CardProductSummary
    | CardWebinar
  )[];
  [k: string]: unknown;
}
export interface CardResource {
  id: string;
  kind: "card_resource";
  post_id?: string | number;
  ucs_content_id?: ExternalRef;
  content_source_type?: "select-content" | "manual-content";
  content_library_type?: "wordpress" | "ucs";
  headline?: string;
  description?: string;
  badge?: string;
  link_1?: Cta;
  image?: Image;
  card_layout?: ("left" | "right" | "center")[];
  url?: string;
  taxonomy?: Taxonomy;
}
export interface ExternalRef {
  /**
   * content source
   */
  source?: string;
  /**
   * content identifier
   */
  id?: string;
  /**
   * additonal options for the control type and source type
   */
  typeOptions?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface Taxonomy {
  tagsAuto?: Tag[];
  tagsManual?: Tag[];
}
export interface Tag {
  uuid: string;
  tagName: string;
  tagUuid: string;
}
export interface CardHeadshot {
  id: string;
  kind: "card_headshot";
  customer_name: string;
  customer_attribution_role: string;
  customer_attribution_company: string;
  link_1?: Cta;
  image: Image;
}
export interface CardStory {
  id: string;
  kind: "card_story";
  headline?: string;
  description?: string;
  link_1?: Cta;
  image?: Image;
  taxonomy?: Taxonomy;
}
export interface CardQuote {
  id: string;
  kind: "card_quote";
  align_image?: "left" | "right";
  quote_image?: {
    headshot?: Image;
    logo?: Image;
    product?: Image;
    [k: string]: unknown;
  };
  quote_text: string;
  name: string;
  role: string;
  company_name: string;
  link_1?: Cta;
  card_background_type?: Background;
}
export interface CardStatistic {
  id: string;
  kind: "card_statistic";
  counter_animation?: boolean;
  statistic: string;
  caption: string;
  description?: string;
  link_1?: Cta;
  card_background_type?: TopBottomSplit;
}
export interface TopBottomSplit {
  kind: "top_bottom_split_background";
  background_image_top?: Image;
  background_image_bottom?: Image;
}
export interface CardEvent {
  id: string;
  kind: "card_event";
  image: Image;
  headline: string;
  date: string;
  location: string;
  description?: string;
  link_1?: Cta;
}
export interface CardContactUs {
  id: string;
  kind: "card_contactus";
  headline: string;
  description: string;
  icon: Icon;
  link: Link;
  taxonomy?: Taxonomy;
}
export interface CardCategory {
  id: string;
  kind: "card_category";
  headline?: string;
  description?: string;
  icon?: Image;
  link_1?: Link;
  brand_color?: string;
}
export interface CardPricingEdition {
  id: string;
  kind: "card_pricingedition";
  headline?: string;
  description?: string;
  link_1?: Cta;
  content_source_type?: "select-content" | "manual-content";
  content_library_type?: "ucs";
  ucs_content_id?: ExternalRef;
  ucs_source_id?: string;
  product_color?: string;
  price?: {
    price_type?: "amount" | "description";
    currency_number_style?: CurrencyNumberStyle;
    amount?: string;
    description?: string;
    [k: string]: unknown;
  };
  price_suffix?: {
    suffix_type?: "user_month" | "user_year" | "other";
    text?: string;
    [k: string]: unknown;
  };
  price_subtext?: {
    subtext_type?: "usd_annually" | "other";
    text?: string;
    [k: string]: unknown;
  };
  /**
   * @minItems 1
   * @maxItems 3
   */
  feature_list?: {
    description?: string;
    additional_information?: string;
  }[];
}
export interface CardLogomark {
  id: string;
  kind: "card_logomark";
  image?: Image;
  link?: Link;
  content_source_type?: "select-content" | "manual-content";
  content_library_type?: "ucs";
  ucs_content_id?: ExternalRef;
}
export interface CardShowHide {
  id: string;
  kind: "card_showhide";
  headline: string;
  description: string;
  media?: Media;
}
export interface Media {
  image?: Image;
  video?: Video;
}
export interface Vidyard {
  video_type?: "vidyard";
  label?: string;
  uuid: string;
}
export interface Kaltura {
  video_type: "kaltura";
  label?: string;
  uuid: string;
}
export interface Html5 {
  video_type: "html5";
  loop_video?: boolean;
  desktop_poster_image?: Image;
  desktop_video_1_url: string;
  desktop_video_2_url?: string;
  tablet_portrait_poster_image?: Image;
  tablet_portrait_video_1_url: string;
  tablet_portrait_video_2_url?: string;
}
export interface Youtube {
  video_type: "youtube";
  label?: string;
  uuid: string;
  autoplay?: boolean;
}
export interface CardProduct {
  id: string;
  kind: "card_product";
  image?: Icon | Image;
  label?: string;
  link?: Link;
  content_source_type?: "select-content" | "manual-content";
  content_library_type?: "ucs";
  ucs_content_id?: ExternalRef;
}
export interface CardProductAddon {
  id: string;
  kind: "card_productaddon";
  headline?: string;
  description?: string;
  link_1?: Cta;
  content_source_type?: "select-content" | "manual-content";
  content_library_type?: "ucs";
  ucs_content_id?: ExternalRef;
  product_variation_type?: string;
  product_color?: string;
  price?: {
    price_type?: "amount" | "description";
    currency_number_style?: CurrencyNumberStyle;
    amount?: string;
    description?: string;
    [k: string]: unknown;
  };
  price_suffix?: {
    suffix_type?: "user_month" | "user_year" | "other";
    text?: string;
    [k: string]: unknown;
  };
}
export interface CardProductAddonAnchor {
  id: string;
  kind: "card_productaddon-anchor";
  headline: string;
  description?: string;
  link_1: Cta;
  link_2?: Cta;
  product_color: string;
  image?: Image;
  price?: {
    price_type?: "amount" | "description";
    currency_number_style?: CurrencyNumberStyle;
    amount?: string;
    description?: string;
    [k: string]: unknown;
  };
  price_suffix?: {
    suffix_type?: "user_month" | "user_year" | "other";
    text?: string;
    [k: string]: unknown;
  };
}
export interface CardProductSummary {
  id: string;
  kind: "card_product-summary";
  image?: Icon;
  label?: string;
  link?: Link;
}
export interface CardWebinar {
  id: string;
  kind: "card_webinar";
  ucs_content_id?: ExternalRef;
  content_source_type?: "select-content";
  content_library_type?: "ucs";
  headline?: string;
  startDate?: string;
  endDate?: string;
  duration?: string;
  description?: string;
  badge?: string;
  link_1?: Cta;
  image?: Image;
  taxonomy?: Taxonomy;
}
export interface Comparisontable {
  attributes?: {
    audience_segment?: string[];
    theme_variant?: string;
    minimize_blade_spacing_bottom?: boolean;
    minimize_blade_spacing?: boolean;
    experiment_id?: string;
    experiment_type?: string;
    headline: string;
    headline_font_color?: string;
    anchor_id?: string;
    ucs_content_id: ExternalRef;
    link_1?: Link;
    link_2?: Link;
    blade_background_type?: Background;
    esi_blade_flag?: string;
    esi_blade_variant?: string;
    esi_blade_rule?: string;
  };
  name: "sf/comparisontable";
  id: string;
  media_items?: FeatureComparisonGroup[];
  [k: string]: unknown;
}
export interface FeatureComparisonGroup {
  id: string;
  name: string;
  /**
   * @minItems 1
   * @maxItems 20
   */
  features: {
    name: string;
    description?: string;
    editionStatus?: {
      editionId: string;
      editionStatus: string;
      overrideText?: string;
      [k: string]: unknown;
    }[];
    [k: string]: unknown;
  }[];
}
export interface Contactus {
  attributes?: {
    audience_segment?: string[];
    theme_variant?: string;
    minimize_blade_spacing_bottom?: boolean;
    minimize_blade_spacing?: boolean;
    experiment_id?: string;
    experiment_type?: string;
    headline: string;
    headline_font_color?: string;
    anchor_id?: string;
    blade_background_type?: Background;
    esi_blade_flag?: string;
    esi_blade_variant?: string;
    esi_blade_rule?: string;
  };
  name: "sf/contactus";
  id: string;
  media_items?: CardContactUs[];
  [k: string]: unknown;
}
export interface Contiguouscontainer {
  attributes?: {
    audience_segment?: string[];
    theme_variant?: string;
    anchor_id?: string;
    blade_background_type?: Background;
  };
  name: "sf/contiguouscontainer";
  id: string;
  media_items?: ChildrenContiguousContainer[];
  [k: string]: unknown;
}
export interface ChildrenContiguousContainer {
  id: string;
  label: string;
  kind: "children_contiguous-container";
  blades: (
    | Agenda
    | Author
    | Comparisontable
    | Contactus
    | Faq
    | Footnote
    | Index
    | Logogrid
    | Marquee
    | Media1
    | Notification
    | Nup
    | Nupfixed
    | Offer
    | Oneup
    | Productfeature
    | Productportfolio
    | Promotion
    | Simpletable
    | Story
    | Summary
    | Text
    | Textlongform
    | Textmainbody
    | Trailheadmfe
  )[];
}
export interface Faq {
  attributes?: {
    audience_segment?: string[];
    theme_variant?: string;
    minimize_blade_spacing_bottom?: boolean;
    minimize_blade_spacing?: boolean;
    experiment_id?: string;
    experiment_type?: string;
    headline: string;
    headline_font_color?: string;
    anchor_id?: string;
    blade_background_type?: Background;
    esi_blade_flag?: string;
    esi_blade_variant?: string;
    esi_blade_rule?: string;
  };
  name: "sf/faq";
  id: string;
  tab_items?: CardFAQCategory[];
  [k: string]: unknown;
}
export interface CardFAQCategory {
  id: string;
  kind: "card_faq-category";
  label: string;
  /**
   * @minItems 1
   * @maxItems 4
   */
  content: AccordionGroup[];
}
export interface AccordionGroup {
  id?: string;
  kind: "accordion_group";
  accordions: {
    headline: string;
    description: string;
    [k: string]: unknown;
  }[];
}
export interface Footnote {
  attributes?: {
    blade_layout?: string;
    audience_segment?: string[];
    theme_variant?: string;
    minimize_blade_spacing_bottom?: boolean;
    minimize_blade_spacing?: boolean;
    experiment_id?: string;
    experiment_type?: string;
    footnote_text: string;
    anchor_id?: string;
    column_grid?: string;
    esi_blade_flag?: string;
    esi_blade_variant?: string;
    esi_blade_rule?: string;
  };
  name: "sf/footnote";
  id: string;
  [k: string]: unknown;
}
export interface Index {
  attributes?: {
    audience_segment?: string[];
    theme_variant?: string;
    minimize_blade_spacing_bottom?: boolean;
    minimize_blade_spacing?: boolean;
    experiment_id?: string;
    experiment_type?: string;
    headline: string;
    headline_font_color?: string;
    anchor_id?: string;
    card_type: string;
    card_source?: string;
    blade_background_type?: Background;
    esi_blade_flag?: string;
    esi_blade_variant?: string;
    esi_blade_rule?: string;
  };
  name: "sf/index";
  id: string;
  media_items?: (CardResource | CardWebinar)[];
  media_items_count?: number;
  filters?: IndexBladeFilters;
  [k: string]: unknown;
}
export interface FilterGroup {
  type?: string;
  name?: string;
  label?: string;
  options?: FilterGroupOption[];
  [k: string]: unknown;
}
export interface FilterGroupOption {
  id?: string;
  label?: string;
  [k: string]: unknown;
}
export interface Logogrid {
  attributes?: {
    audience_segment?: string[];
    theme_variant?: string;
    minimize_blade_spacing_bottom?: boolean;
    minimize_blade_spacing?: boolean;
    experiment_id?: string;
    experiment_type?: string;
    card_type: string;
    card_link_visibility?: ToggleControl;
    grid_type?: string;
    logo_ticker_title?: string;
    eyebrow?: Eyebrow;
    headline: string;
    headline_font_color?: string;
    description?: string;
    anchor_id?: string;
    link_1?: Cta;
    link_2?: Cta;
    blade_background_type?: Background;
    esi_blade_flag?: string;
    esi_blade_variant?: string;
    esi_blade_rule?: string;
  };
  name: "sf/logogrid";
  id: string;
  media_items?: (CardLogomark | CardProduct)[];
  [k: string]: unknown;
}
export interface Marquee {
  attributes?: {
    blade_layout: string;
    two_column_spacing?: string;
    audience_segment?: string[];
    image_overflow?: boolean;
    theme_variant?: string;
    minimize_blade_spacing_bottom?: boolean;
    minimize_blade_spacing?: boolean;
    experiment_id?: string;
    experiment_type?: string;
    eyebrow?: Eyebrow;
    use_eyebrow_as_headline?: boolean;
    headline: string;
    headline_font_color?: string;
    headline_size?: string;
    description?: string;
    anchor_id?: string;
    link_1?: Cta;
    link_2?: Cta;
    media?: Media;
    blade_background_type?: Background;
    esi_blade_flag?: string;
    esi_blade_variant?: string;
    esi_blade_rule?: string;
  };
  name: "sf/marquee";
  id: string;
  [k: string]: unknown;
}
export interface Media1 {
  attributes?: {
    audience_segment?: string[];
    experiment_id?: string;
    experiment_type?: string;
    theme_variant?: string;
    minimize_blade_spacing_bottom?: boolean;
    minimize_blade_spacing?: boolean;
    media?: Media;
    viz?: string;
    caption?: {
      style?: string;
      content?: string;
    };
    headline_font_color?: string;
    anchor_id?: string;
    link_1?: Cta;
    link_2?: Cta;
    blade_background_type?: Background;
    esi_blade_flag?: string;
    esi_blade_variant?: string;
    esi_blade_rule?: string;
  };
  name: "sf/media";
  id: string;
  [k: string]: unknown;
}
export interface Notification {
  attributes?: {
    audience_segment?: string[];
    experiment_id?: string;
    experiment_type?: string;
    image?: Image;
    headline: string;
    headline_color?: string;
    anchor_id?: string;
    link?: Link;
    blade_background_hex_color: string;
    esi_blade_flag?: string;
    esi_blade_variant?: string;
    esi_blade_rule?: string;
  };
  name: "sf/notification";
  id: string;
  [k: string]: unknown;
}
export interface Nup {
  attributes?: {
    link_location: string;
    audience_segment?: string[];
    theme_variant?: string;
    minimize_blade_spacing_bottom?: boolean;
    minimize_blade_spacing?: boolean;
    experiment_id?: string;
    experiment_type?: string;
    card_type: string;
    card_layout?: string;
    grid_type?: string;
    card_description_visibility?: ToggleControl;
    anchor_id?: string;
    card_image?: ToggleControl;
    card_eyebrow_visibility?: ToggleControl;
    card_link_visibility?: ToggleControl;
    eyebrow?: Eyebrow;
    headline?: string;
    headline_font_color?: string;
    description?: string;
    link_1?: Cta;
    link_2?: Cta;
    legal?: string;
    blade_background_type?: Background;
    esi_blade_flag?: string;
    esi_blade_variant?: string;
    esi_blade_rule?: string;
  };
  name: "sf/nup";
  id: string;
  media_items?: (CardResource | CardHeadshot | CardQuote | CardStatistic | CardEvent | CardWebinar)[];
  [k: string]: unknown;
}
export interface Nupfixed {
  attributes?: {
    audience_segment?: string[];
    theme_variant?: string;
    minimize_blade_spacing_bottom?: boolean;
    minimize_blade_spacing?: boolean;
    experiment_id?: string;
    experiment_type?: string;
    link_location?: string;
    headline: string;
    headline_font_color?: string;
    description?: string;
    anchor_id?: string;
    card_type: string;
    currency_selector?: ToggleControl;
    card_style?: string;
    link_1?: Cta;
    legal?: string;
    blade_background_type?: Background;
    esi_blade_flag?: string;
    esi_blade_variant?: string;
    esi_blade_rule?: string;
  };
  name: "sf/nupfixed";
  id: string;
  media_items?: (CardPricingEdition | CardProductAddon | CardSuccessPlan | CardCategory)[];
  [k: string]: unknown;
}
export interface CardSuccessPlan {
  id: string;
  kind: "card_successplan";
  headline?: string;
  description?: string;
  link_1?: Cta;
  content_source_type?: "select-content" | "manual-content";
  content_library_type?: "ucs";
  ucs_content_id?: ExternalRef;
  ucs_source_id?: string;
  price?: {
    price_type?: "amount" | "description";
    currency_number_style?: CurrencyNumberStyle;
    amount?: string;
    description?: string;
    [k: string]: unknown;
  };
  price_suffix?: {
    suffix_type?: "user_month" | "user_year" | "other";
    text?: string;
    [k: string]: unknown;
  };
  price_subtext?: {
    subtext_type?: "usd_annually" | "other";
    text?: string;
    [k: string]: unknown;
  };
  /**
   * @minItems 1
   * @maxItems 4
   */
  feature_list?: {
    description?: string;
    additional_information?: string;
  }[];
}
export interface Offer {
  attributes?: {
    blade_layout?: string;
    audience_segment?: string[];
    theme_variant?: string;
    minimize_blade_spacing_bottom?: boolean;
    minimize_blade_spacing?: boolean;
    experiment_id?: string;
    experiment_type?: string;
    offer_id: string;
    blade_background_type?: Background;
    curLocale?: string;
    cdnEnvTag?: string;
    esi_blade_flag?: string;
    esi_blade_variant?: string;
    esi_blade_rule?: string;
  };
  name: "sf/offer";
  id: string;
  [k: string]: unknown;
}
export interface Oneup {
  attributes?: {
    blade_layout: string;
    audience_segment?: string[];
    theme_variant?: string;
    minimize_blade_spacing_bottom?: boolean;
    minimize_blade_spacing?: boolean;
    experiment_id?: string;
    experiment_type?: string;
    eyebrow?: Eyebrow;
    headline: string;
    headline_font_color?: string;
    description?: string;
    anchor_id?: string;
    link_1?: Cta;
    link_2?: Cta;
    media: Media;
    blade_background_type?: Background;
    esi_blade_flag?: string;
    esi_blade_variant?: string;
    esi_blade_rule?: string;
  };
  name: "sf/oneup";
  id: string;
  [k: string]: unknown;
}
export interface Productfeature {
  attributes?: {
    blade_layout?: string;
    audience_segment?: string[];
    theme_variant?: string;
    minimize_blade_spacing_bottom?: boolean;
    minimize_blade_spacing?: boolean;
    experiment_id?: string;
    experiment_type?: string;
    headline: string;
    headline_font_color?: string;
    description?: string;
    anchor_id?: string;
    link_1?: Cta;
    link_2?: Cta;
    blade_background_type?: Background;
    esi_blade_flag?: string;
    esi_blade_variant?: string;
    esi_blade_rule?: string;
  };
  name: "sf/productfeature";
  id: string;
  media_items?: CardShowHide[];
  [k: string]: unknown;
}
export interface Productportfolio {
  attributes?: {
    audience_segment?: string[];
    theme_variant?: string;
    minimize_blade_spacing_bottom?: boolean;
    minimize_blade_spacing?: boolean;
    experiment_id?: string;
    experiment_type?: string;
    layout?: string;
    card_type: string;
    card_style?: string;
    content_source_type?: string;
    content_library_type?: string;
    ucs_content_id?: ExternalRef;
    headline?: string;
    headline_font_color?: string;
    anchor_product_visibility: ToggleControl;
    secondary_headline?: string;
    anchor_id?: string;
    link_1?: Cta;
    blade_background_type?: Background;
    esi_blade_flag?: string;
    esi_blade_variant?: string;
    esi_blade_rule?: string;
  };
  name: "sf/productportfolio";
  id: string;
  media_items?: (ProductCategoryGroup | CardProductAddonAnchor | RelatedProductsGroup)[];
  [k: string]: unknown;
}
export interface ProductCategoryGroup {
  id?: string;
  kind: "product_category_group";
  categories?: {
    id: string;
    kind: "card_product-category";
    title: string;
    dropdown_link_label: string;
    link_1?: Cta;
    cards: (CardProductAddon | CardCategory)[];
    [k: string]: unknown;
  }[];
}
export interface RelatedProductsGroup {
  id?: string;
  kind: "related_products_group";
  cards?: (CardProductAddon | CardCategory)[];
}
export interface Promotion {
  attributes?: {
    blade_layout: string;
    audience_segment?: string[];
    theme_variant?: string;
    minimize_blade_spacing_bottom?: boolean;
    minimize_blade_spacing?: boolean;
    experiment_id?: string;
    experiment_type?: string;
    headline: string;
    description?: string;
    anchor_id?: string;
    image: Image;
    link_1: Cta;
    link_2?: Cta;
    blade_background_type?: Background;
    esi_blade_flag?: string;
    esi_blade_variant?: string;
    esi_blade_rule?: string;
  };
  name: "sf/promotion";
  id: string;
  [k: string]: unknown;
}
export interface Simpletable {
  attributes?: {
    blade_width: string;
    audience_segment?: string[];
    minimize_blade_spacing_bottom?: boolean;
    minimize_blade_spacing?: boolean;
    experiment_id?: string;
    experiment_type?: string;
    headline: string;
    description?: string;
    anchor_id?: string;
    blade_background_type?: Background;
    esi_blade_flag?: string;
    esi_blade_variant?: string;
    esi_blade_rule?: string;
  };
  name: "sf/simpletable";
  id: string;
  media_items?: Table[];
  [k: string]: unknown;
}
export interface Table {
  id: string;
  kind: "table";
  head?: TableSection;
  body?: TableSection;
  foot?: TableSection;
  row_headings?: boolean;
  striped_rows?: boolean;
}
export interface TableCell {
  align?: string;
  content?: string;
  tooltip?: string;
}
export interface Story {
  attributes?: {
    audience_segment?: string[];
    theme_variant?: string;
    minimize_blade_spacing_bottom?: boolean;
    minimize_blade_spacing?: boolean;
    experiment_id?: string;
    experiment_type?: string;
    blade_headline_block_alignment?: string;
    card_text_alignment?: string;
    card_image_visibility?: ToggleControl;
    card_title_visibility?: ToggleControl;
    card_description_visibility?: ToggleControl;
    anchor_id?: string;
    card_link_visibility?: ToggleControl;
    eyebrow?: Eyebrow;
    headline?: string;
    headline_font_color?: string;
    description?: string;
    link_1?: Cta;
    link_2?: Cta;
    blade_background_type?: Background;
    esi_blade_flag?: string;
    esi_blade_variant?: string;
    esi_blade_rule?: string;
  };
  name: "sf/story";
  id: string;
  media_items?: CardStory[];
  [k: string]: unknown;
}
export interface Summary {
  attributes?: {
    audience_segment?: string[];
    theme_variant?: string;
    minimize_blade_spacing_bottom?: boolean;
    minimize_blade_spacing?: boolean;
    experiment_id?: string;
    experiment_type?: string;
    summary_story: string;
    summary_about?: string;
    summary_industry?: {
      industry_icon?: string;
      industry_icon_url?: string;
    };
    anchor_id?: string;
    blade_background_type?: Background;
    esi_blade_flag?: string;
    esi_blade_variant?: string;
    esi_blade_rule?: string;
  };
  name: "sf/summary";
  id: string;
  media_items?: CardProductSummary[];
  [k: string]: unknown;
}
export interface Text {
  attributes?: {
    chapter_designation?: ToggleControl;
    chapter_summary?: string;
    generic_lists?: {
      lists_layout?: string;
      link_location?: string;
    };
    blade_layout: string;
    audience_segment?: string[];
    theme_variant?: string;
    minimize_blade_spacing_bottom?: boolean;
    minimize_blade_spacing?: boolean;
    experiment_id?: string;
    experiment_type?: string;
    eyebrow?: Eyebrow;
    headline: string;
    headline_font_color?: string;
    description?: string;
    anchor_id?: string;
    link_1?: Cta;
    link_2?: Cta;
    blade_background_type?: Background;
    headline_size?: string;
    column_grid?: string;
    esi_blade_flag?: string;
    esi_blade_variant?: string;
    esi_blade_rule?: string;
    chapter_number?: string;
  };
  name: "sf/text";
  id: string;
  tab_items?: CardListColumn[];
  [k: string]: unknown;
}
export interface CardListColumn {
  id: string;
  kind: "card_list-column";
  label: string;
  /**
   * @minItems 1
   * @maxItems 4
   */
  media_items: CardListItem[];
}
export interface CardListItem {
  id: string;
  kind: "card_list-item";
  headline: string;
  description?: string;
  link_1?: Cta;
}
export interface Textlongform {
  attributes?: {
    blade_layout: string;
    audience_segment?: string[];
    theme_variant?: string;
    minimize_blade_spacing_bottom?: boolean;
    minimize_blade_spacing?: boolean;
    experiment_id?: string;
    experiment_type?: string;
    eyebrow?: Eyebrow;
    headline?: string;
    headline_font_color?: string;
    description?: string;
    anchor_id?: string;
    link_1?: Cta;
    link_2?: Cta;
    blade_background_type?: Background;
    headline_size?: string;
    column_grid?: string;
    esi_blade_flag?: string;
    esi_blade_variant?: string;
    esi_blade_rule?: string;
  };
  name: "sf/textlongform";
  id: string;
  [k: string]: unknown;
}
export interface Textmainbody {
  attributes?: {
    audience_segment?: string[];
    theme_variant?: string;
    minimize_blade_spacing_bottom?: boolean;
    minimize_blade_spacing?: boolean;
    experiment_id?: string;
    experiment_type?: string;
    headline?: string;
    headline_font_color?: string;
    headline_size?: string;
    description: string;
    anchor_id?: string;
    blade_background_type?: Background;
    esi_blade_flag?: string;
    esi_blade_variant?: string;
    esi_blade_rule?: string;
  };
  name: "sf/textmainbody";
  id: string;
  [k: string]: unknown;
}
export interface Trailheadmfe {
  attributes?: {
    audience_segment?: string[];
    theme_variant?: string;
    minimize_blade_spacing_bottom?: boolean;
    minimize_blade_spacing?: boolean;
    experiment_id?: string;
    experiment_type?: string;
    link_location: string;
    eyebrow?: Eyebrow;
    headline?: string;
    headline_font_color?: string;
    description?: string;
    anchor_id?: string;
    trailhead_module_1: string;
    trailhead_module_2: string;
    trailhead_module_3: string;
    variant: string;
    personalization_id?: string;
    allow_english_fallback?: boolean;
    link_1?: Cta;
    link_2?: Cta;
    blade_background_type?: Background;
    esi_blade_flag?: string;
    esi_blade_variant?: string;
    esi_blade_rule?: string;
  };
  name: "sf/trailheadmfe";
  id: string;
  [k: string]: unknown;
}
export interface Form {
  attributes?: {
    form_type: string;
    layout_variant?: string;
    blade_layout?: string;
    audience_segment?: string[];
    minimize_blade_spacing_bottom?: boolean;
    minimize_blade_spacing?: boolean;
    experiment_id?: string;
    experiment_type?: string;
    form_config_id: string;
    eyebrow_image?: Image;
    headline: string;
    subhead?: string;
    description?: string;
    form_headline?: string;
    form_subhead?: string;
    hero_image?: Image;
    anchor_id?: string;
    offer_type: string;
    form_campaign_id: string;
    partner_promo_code?: {
      promo_type?: string;
      text?: string;
    };
    m_cloud_form_name?: string;
    link_1?: Link;
    image?: Image;
    blade_background_type?: Background;
    contact_info?: string;
    curLocale?: string;
    cdnEnvTag?: string;
    esi_blade_flag?: string;
    esi_blade_variant?: string;
    esi_blade_rule?: string;
  };
  name: "sf/form";
  id: string;
  [k: string]: unknown;
}
export interface Helloworld {
  attributes?: {
    blade_layout: string;
    audience_segment?: string[];
    eyebrow?: Eyebrow;
    headline: string;
    headline_size?: string;
    description?: string;
    anchor_id?: string;
    link_1?: Cta;
    link_2?: Cta;
    media?: Media;
    blade_background_type?: Background;
  };
  name: "sf/helloworld";
  id: string;
  [k: string]: unknown;
}
export interface Horizontaltabs {
  attributes?: {
    audience_segment?: string[];
    theme_variant?: string;
    minimize_blade_spacing_bottom?: boolean;
    minimize_blade_spacing?: boolean;
    experiment_id?: string;
    experiment_type?: string;
    headline: string;
    headline_font_color?: string;
    anchor_id?: string;
    blade_background_type?: Background;
    esi_blade_flag?: string;
    esi_blade_variant?: string;
    esi_blade_rule?: string;
  };
  name: "sf/horizontaltabs";
  id: string;
  tab_items?: CardTabsCategory[];
  [k: string]: unknown;
}
export interface CardTabsCategory {
  id: string;
  label: string;
  kind: "card_tabs-category";
  blades: (Oneup | Contactus | Logogrid | Nup | Nupfixed | Text | Media1 | Textmainbody | Promotion | Story)[];
}
export interface Open {
  attributes?: {
    audience_segment?: string[];
    minimize_blade_spacing_bottom?: boolean;
    minimize_blade_spacing?: boolean;
    experiment_id?: string;
    experiment_type?: string;
    styles?: string;
    external_styles?: string;
    external_scripts?: string;
    external_scripts_modules?: string;
    markup: string;
    anchor_id?: string;
    esi_blade_flag?: string;
    esi_blade_variant?: string;
    esi_blade_rule?: string;
  };
  name: "sf/open";
  id: string;
  [k: string]: unknown;
}
export interface Tableofcontents {
  attributes?: {
    audience_segment?: string[];
    minimize_blade_spacing_bottom?: boolean;
    minimize_blade_spacing?: boolean;
    experiment_id?: string;
    experiment_type?: string;
    anchor_id?: string;
    esi_blade_flag?: string;
    esi_blade_variant?: string;
    esi_blade_rule?: string;
  };
  name: "sf/tableofcontents";
  id: string;
  media_items?: CardChapter[];
  [k: string]: unknown;
}
export interface CardChapter {
  id?: string;
  anchor_id?: string;
  headline: string;
  chapter_summary?: string;
}
export interface Textwithimage {
  attributes?: {
    image?: Image;
    title?: string;
    description: string;
    anchor_id?: string;
  };
  name: "sf/textwithimage";
  id: string;
  [k: string]: unknown;
}
export interface Videoblade {
  attributes?: {
    video_type?: string;
    autoplay?: boolean;
    video_id?: string;
    video_label?: string;
    headline?: string;
    description?: string;
    anchor_id?: string;
    link_1?: Cta;
    link_2?: Cta;
  };
  name: "sf/videoblade";
  id: string;
  [k: string]: unknown;
}
export interface PageBackground {
  kind: "page_standard_background";
  page_background_color?: string;
  page_background_image?: Image;
  page_background_image_position?: string;
  page_background_shape?: string;
  page_background_gradient_direction?: string;
}
export interface Footer {
  footerType?: string;
  [k: string]: unknown;
}
